//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FinalCert {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinalCert() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FinalCert", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Proceed.
        /// </summary>
        internal static string CannotProceed {
            get {
                return ResourceManager.GetString("CannotProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you change your mind about opting out at any time or have questions in this regard, call the ADAP helpdesk at (303)692-2716 for assistance..
        /// </summary>
        internal static string IfChangeMind {
            get {
                return ResourceManager.GetString("IfChangeMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Sharing.
        /// </summary>
        internal static string InfoSharingHeader {
            get {
                return ResourceManager.GetString("InfoSharingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Colorado ADAP has developed a system to share some of the information you provide to ADAP with participating HIV service providers and case managers.  ADAP will not be sharing your name, case management or any other type of service notes – your information will be disguised by a code. If you participate, you won’t have to recertify at any other Ryan White agency- just with the ADAP. &lt;/p&gt;
        ///
        ///&lt;p&gt;Shared data includes your ADAP certification start and end dates, income, insurance, housing status, residential [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InfoSharingText {
            get {
                return ResourceManager.GetString("InfoSharingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must check either &quot;Opt-in&quot; or &quot;Opt-out&quot;.
        /// </summary>
        internal static string MustOptInOrOut {
            get {
                return ResourceManager.GetString("MustOptInOrOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since you checked &quot;Opt-out&quot;, you must enter the date.
        /// </summary>
        internal static string OptInSoNeedDate {
            get {
                return ResourceManager.GetString("OptInSoNeedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since you checked &quot;Opt-out&quot;, you must enter your full name.
        /// </summary>
        internal static string OptInSoNeedName {
            get {
                return ResourceManager.GetString("OptInSoNeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since you checked &quot;Opt-out&quot;, you must enter both your full name and the date.
        /// </summary>
        internal static string OptInSoNeedNameAndDate {
            get {
                return ResourceManager.GetString("OptInSoNeedNameAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECERTIFY WITH ONE AND YOU’RE DONE!.
        /// </summary>
        internal static string RecertWithOneAndDone {
            get {
                return ResourceManager.GetString("RecertWithOneAndDone", resourceCulture);
            }
        }
    }
}
