//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Validation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you checked &quot;yes&quot; indicating that you would upload a premium invoice, but no invoice was uploaded..
        /// </summary>
        internal static string CheckedYesButNoInvoice {
            get {
                return ResourceManager.GetString("CheckedYesButNoInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you indicated that you are enrolled in Medicare Part A, but you did not indicate an effective date..
        /// </summary>
        internal static string MedicareANoDate {
            get {
                return ResourceManager.GetString("MedicareANoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you indicated that you are enrolled in Medicare Part B, but you did not indicate an effective date..
        /// </summary>
        internal static string MedicareBNoDate {
            get {
                return ResourceManager.GetString("MedicareBNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must check at least one option under section.
        /// </summary>
        internal static string MustCheckOneUnderSection_ {
            get {
                return ResourceManager.GetString("MustCheckOneUnderSection_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must complete all fields under.
        /// </summary>
        internal static string MustCompleteAllFieldsUnder_ {
            get {
                return ResourceManager.GetString("MustCompleteAllFieldsUnder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must enter at least one case manager/social worker name.
        /// </summary>
        internal static string MustEnterCaseWorker {
            get {
                return ResourceManager.GetString("MustEnterCaseWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you selected &quot;Other&quot;, you must provide an explanation.
        /// </summary>
        internal static string MustExplainOther {
            get {
                return ResourceManager.GetString("MustExplainOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you selected &quot;other&quot; as a preferred language, you must add an explanation.
        /// </summary>
        internal static string MustExplainOtherLang {
            get {
                return ResourceManager.GetString("MustExplainOtherLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must make a selection for &quot;does your employer offer health insurance?&quot;.
        /// </summary>
        internal static string MustSelectEmployerInsOpt {
            get {
                return ResourceManager.GetString("MustSelectEmployerInsOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since you indicated that you&apos;re not enrolled in your employer&apos;s health insurance, you must provide a reason.
        /// </summary>
        internal static string NeeedReasonNotEnrolledEmpIns {
            get {
                return ResourceManager.GetString("NeeedReasonNotEnrolledEmpIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not attach proof of residency..
        /// </summary>
        internal static string NoProofResidency {
            get {
                return ResourceManager.GetString("NoProofResidency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Validation Problems.
        /// </summary>
        internal static string OtherValProblems {
            get {
                return ResourceManager.GetString("OtherValProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proof of income.
        /// </summary>
        internal static string ProofOfIncome {
            get {
                return ResourceManager.GetString("ProofOfIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramsell ID requires an 11 digit number..
        /// </summary>
        internal static string RamsellID11Digits {
            get {
                return ResourceManager.GetString("RamsellID11Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections Missing Required Responses.
        /// </summary>
        internal static string SctMissingReqRsps {
            get {
                return ResourceManager.GetString("SctMissingReqRsps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections Missing Required Responses.
        /// </summary>
        internal static string SctMissingRsps {
            get {
                return ResourceManager.GetString("SctMissingRsps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you indicated that you identify as Asian,.
        /// </summary>
        internal static string SinceAsian_ {
            get {
                return ResourceManager.GetString("SinceAsian_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you selected employment status &quot;other&quot;, you must add a description.
        /// </summary>
        internal static string SinceEmpOtherMustSpecify {
            get {
                return ResourceManager.GetString("SinceEmpOtherMustSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since you indicated having an employer,.
        /// </summary>
        internal static string SinceHaveEmp_ {
            get {
                return ResourceManager.GetString("SinceHaveEmp_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you indicated &quot;Hispanic / Latino(a)&quot; for ethnicity,.
        /// </summary>
        internal static string SinceHispanic_ {
            get {
                return ResourceManager.GetString("SinceHispanic_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since you selected income type &quot;Employment&quot;, you must complete all fields in this section.
        /// </summary>
        internal static string SinceIncomeEmpMustComplete {
            get {
                return ResourceManager.GetString("SinceIncomeEmpMustComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since you selected income type &quot;other&quot;, you must specify in text.
        /// </summary>
        internal static string SinceIncomOtherMustSpecify {
            get {
                return ResourceManager.GetString("SinceIncomOtherMustSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you indicated that you identify as a Native Hawaiian or Pacific Islander,.
        /// </summary>
        internal static string SinceIslander_ {
            get {
                return ResourceManager.GetString("SinceIslander_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you indicated that your mail address is NOT the same as your residential address,.
        /// </summary>
        internal static string SinceMailNotResid_ {
            get {
                return ResourceManager.GetString("SinceMailNotResid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to since you indicated that you are on Medicare, you must check Part A and/or Part B..
        /// </summary>
        internal static string SinceMedicareMustCheckAOrB {
            get {
                return ResourceManager.GetString("SinceMedicareMustCheckAOrB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you checked &quot;yes&quot; under.
        /// </summary>
        internal static string SinceYesUnder_ {
            get {
                return ResourceManager.GetString("SinceYesUnder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;d like to go back and correct before submitting.
        /// </summary>
        internal static string SubmitWithErrorsCancel {
            get {
                return ResourceManager.GetString("SubmitWithErrorsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, submit incomplete application.
        /// </summary>
        internal static string SubmitWithErrorsConfirm {
            get {
                return ResourceManager.GetString("SubmitWithErrorsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit with Errors.
        /// </summary>
        internal static string SubmitWithErrorsHeader {
            get {
                return ResourceManager.GetString("SubmitWithErrorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to submit an incomplete application, an ADAP staff may reach out to you and ask you to correct missing items before processing your application. Are you sure you want to submit.
        /// </summary>
        internal static string SubmitWithErrorsPrompt {
            get {
                return ResourceManager.GetString("SubmitWithErrorsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Errors.
        /// </summary>
        internal static string ValidationErrors {
            get {
                return ResourceManager.GetString("ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation passed with no issues..
        /// </summary>
        internal static string ValidPassed {
            get {
                return ResourceManager.GetString("ValidPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Warnings&lt;/b&gt; (While these items will not prevent you from submitting your application, you may get a call from an ADAP staff member requesting these items be completed in order to extend your eligibility for services.).
        /// </summary>
        internal static string WarningsHeader {
            get {
                return ResourceManager.GetString("WarningsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must complete.
        /// </summary>
        internal static string YouMustComplete_ {
            get {
                return ResourceManager.GetString("YouMustComplete_", resourceCulture);
            }
        }
    }
}
