//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Nullable<int> ent_id { get; set; }
        public long AddressID { get; set; }
        public Nullable<long> ContactID { get; set; }
        public Nullable<int> ProviderIntID { get; set; }
        public string AddressType { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public string StateRegion { get; set; }
        public string Zip { get; set; }
        public string ZipExt { get; set; }
        public string County { get; set; }
        public string CtyCode { get; set; }
        public string Directions { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
        public string Sts { get; set; }
    }
}
