//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_SubSections
    {
        public def_SubSections()
        {
            this.def_SectionItems = new HashSet<def_SectionItems>();
        }
    
        public virtual int subSectionId { get; set; }
        public virtual int sectionId { get; set; }
        public bool Cache { get; set; }
    
        public virtual ICollection<def_SectionItems> def_SectionItems { get; set; }
        public virtual def_Sections def_Sections { get; set; }
    }
}
