//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_FormParts
    {
        public virtual int formPartId { get; set; }
        public virtual int formId { get; set; }
        public virtual int partId { get; set; }
        public virtual Nullable<short> order { get; set; }
        public bool Cache { get; set; }
    
        public virtual def_Forms def_Forms { get; set; }
        public virtual def_Parts def_Parts { get; set; }
    }
}
