//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_ItemResults
    {
        public def_ItemResults()
        {
            this.def_ResponseVariables = new HashSet<def_ResponseVariables>();
        }
    
        public int itemResultId { get; set; }
        public int formResultId { get; set; }
        public int itemId { get; set; }
        public int sessionStatus { get; set; }
        public System.DateTime dateUpdated { get; set; }
    
        public virtual def_FormResults def_FormResults { get; set; }
        public virtual ICollection<def_ResponseVariables> def_ResponseVariables { get; set; }
        public virtual def_Items def_Items { get; set; }
    }
}
