//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_FormResults
    {
        public def_FormResults()
        {
            this.def_ItemResults = new HashSet<def_ItemResults>();
            this.def_AccessLogging = new HashSet<def_AccessLogging>();
            this.def_StatusLog = new HashSet<def_StatusLog>();
        }
    
        public int formResultId { get; set; }
        public int formId { get; set; }
        public byte formStatus { get; set; }
        public byte sessionStatus { get; set; }
        public System.DateTime dateUpdated { get; set; }
        public bool deleted { get; set; }
        public bool locked { get; set; }
        public bool archived { get; set; }
        public Nullable<int> EnterpriseID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> subject { get; set; }
        public Nullable<int> interviewer { get; set; }
        public Nullable<int> assigned { get; set; }
        public bool training { get; set; }
        public byte reviewStatus { get; set; }
        public Nullable<System.DateTime> statusChangeDate { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
    
        public virtual ICollection<def_ItemResults> def_ItemResults { get; set; }
        public virtual def_Forms def_Forms { get; set; }
        public virtual ICollection<def_AccessLogging> def_AccessLogging { get; set; }
        public virtual ICollection<def_StatusLog> def_StatusLog { get; set; }
    }
}
