//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_Forms
    {
        public def_Forms()
        {
            this.def_FormParts = new HashSet<def_FormParts>();
            this.def_FormResults = new HashSet<def_FormResults>();
            this.def_StatusMaster = new HashSet<def_StatusMaster>();
            this.def_FormText = new HashSet<def_FormText>();
        }
    
        public virtual int formId { get; set; }
        public virtual string identifier { get; set; }
        public virtual string title { get; set; }
        public virtual Nullable<int> EnterpriseID { get; set; }
        public bool Cache { get; set; }
    
        public virtual ICollection<def_FormParts> def_FormParts { get; set; }
        public virtual ICollection<def_FormResults> def_FormResults { get; set; }
        public virtual ICollection<def_StatusMaster> def_StatusMaster { get; set; }
        public virtual ICollection<def_FormText> def_FormText { get; set; }
    }
}
