//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_StatusDetail
    {
        public def_StatusDetail()
        {
            this.def_StatusFlow = new HashSet<def_StatusFlow>();
            this.def_StatusFlow1 = new HashSet<def_StatusFlow>();
            this.def_StatusLog = new HashSet<def_StatusLog>();
            this.def_StatusLog1 = new HashSet<def_StatusLog>();
            this.def_StatusText = new HashSet<def_StatusText>();
        }
    
        public int statusDetailId { get; set; }
        public Nullable<int> statusMasterId { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public string identifier { get; set; }
        public string Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual def_StatusMaster def_StatusMaster { get; set; }
        public virtual ICollection<def_StatusFlow> def_StatusFlow { get; set; }
        public virtual ICollection<def_StatusFlow> def_StatusFlow1 { get; set; }
        public virtual ICollection<def_StatusLog> def_StatusLog { get; set; }
        public virtual ICollection<def_StatusLog> def_StatusLog1 { get; set; }
        public virtual ICollection<def_StatusText> def_StatusText { get; set; }
    }
}
