//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_LookupDetail
    {
        public def_LookupDetail()
        {
            this.def_LookupText = new HashSet<def_LookupText>();
        }
    
        public virtual int lookupDetailId { get; set; }
        public virtual int lookupMasterId { get; set; }
        public virtual Nullable<int> EnterpriseID { get; set; }
        public virtual Nullable<int> GroupID { get; set; }
        public virtual int displayOrder { get; set; }
        public virtual string dataValue { get; set; }
        public virtual string StatusFlag { get; set; }
        public bool Cache { get; set; }
    
        public virtual def_LookupMaster def_LookupMaster { get; set; }
        public virtual ICollection<def_LookupText> def_LookupText { get; set; }
    }
}
