//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_ItemVariables
    {
        public def_ItemVariables()
        {
            this.def_ResponseVariables = new HashSet<def_ResponseVariables>();
        }
    
        public virtual int itemVariableId { get; set; }
        public virtual int itemId { get; set; }
        public virtual string identifier { get; set; }
        public virtual short baseTypeId { get; set; }
        public virtual string defaultValue { get; set; }
        public virtual Nullable<int> outcomeDeclarationId { get; set; }
        public bool Cache { get; set; }
    
        public virtual def_BaseTypes def_BaseTypes { get; set; }
        public virtual def_Items def_Items { get; set; }
        public virtual ICollection<def_ResponseVariables> def_ResponseVariables { get; set; }
        public virtual def_OutcomeDeclaration def_OutcomeDeclaration { get; set; }
    }
}
