//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_Sections
    {
        public def_Sections()
        {
            this.def_PartSections = new HashSet<def_PartSections>();
            this.def_SectionItems = new HashSet<def_SectionItems>();
            this.def_SubSections = new HashSet<def_SubSections>();
            this.def_SectionText = new HashSet<def_SectionText>();
        }
    
        public virtual int sectionId { get; set; }
        public virtual string identifier { get; set; }
        public virtual string title { get; set; }
        public virtual bool visible { get; set; }
        public virtual string href { get; set; }
        public virtual Nullable<int> branchRuleId { get; set; }
        public virtual string rubricBlock { get; set; }
        public virtual bool multipleItemsPerPage { get; set; }
        public bool Cache { get; set; }
    
        public virtual def_BranchRules def_BranchRules { get; set; }
        public virtual ICollection<def_PartSections> def_PartSections { get; set; }
        public virtual ICollection<def_SectionItems> def_SectionItems { get; set; }
        public virtual ICollection<def_SubSections> def_SubSections { get; set; }
        public virtual ICollection<def_SectionText> def_SectionText { get; set; }
    }
}
