//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_PartSectionsEnt
    {
        public virtual int partSectionEntId { get; set; }
        public virtual int partSectionId { get; set; }
        public virtual int entPartSectionId { get; set; }
        public virtual int EnterpriseID { get; set; }
        public virtual bool visible { get; set; }
        public bool Cache { get; set; }
    
        public virtual def_PartSections def_PartSections { get; set; }
        public virtual def_PartSections def_PartSections1 { get; set; }
    }
}
