//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_FileAttachment
    {
        public int FileId { get; set; }
        public int EnterpriseId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int AttachTypeId { get; set; }
        public int RelatedId { get; set; }
        public int RelatedEnumId { get; set; }
        public string displayText { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string StatusFlag { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual def_AttachType def_AttachType { get; set; }
        public virtual def_RelatedEnum def_RelatedEnum { get; set; }
    }
}
