//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_Languages
    {
        public def_Languages()
        {
            this.def_Items = new HashSet<def_Items>();
            this.def_LookupText = new HashSet<def_LookupText>();
            this.def_StatusText = new HashSet<def_StatusText>();
            this.def_FormText = new HashSet<def_FormText>();
            this.def_ItemText = new HashSet<def_ItemText>();
            this.def_PartText = new HashSet<def_PartText>();
            this.def_SectionText = new HashSet<def_SectionText>();
        }
    
        public virtual short langId { get; set; }
        public virtual string languageRegion { get; set; }
        public virtual string title { get; set; }
        public bool Cache { get; set; }
    
        public virtual ICollection<def_Items> def_Items { get; set; }
        public virtual ICollection<def_LookupText> def_LookupText { get; set; }
        public virtual ICollection<def_StatusText> def_StatusText { get; set; }
        public virtual ICollection<def_FormText> def_FormText { get; set; }
        public virtual ICollection<def_ItemText> def_ItemText { get; set; }
        public virtual ICollection<def_PartText> def_PartText { get; set; }
        public virtual ICollection<def_SectionText> def_SectionText { get; set; }
    }
}
