//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_BaseTypes
    {
        public def_BaseTypes()
        {
            this.def_ItemVariables = new HashSet<def_ItemVariables>();
            this.def_LookupMaster = new HashSet<def_LookupMaster>();
        }
    
        public virtual short baseTypeId { get; set; }
        public virtual string enumeration { get; set; }
        public bool Cache { get; set; }
    
        public virtual ICollection<def_ItemVariables> def_ItemVariables { get; set; }
        public virtual ICollection<def_LookupMaster> def_LookupMaster { get; set; }
    }
}
