//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_Parts
    {
        public def_Parts()
        {
            this.def_FormParts = new HashSet<def_FormParts>();
            this.def_PartSections = new HashSet<def_PartSections>();
            this.def_PartText = new HashSet<def_PartText>();
        }
    
        public virtual int partId { get; set; }
        public virtual string identifier { get; set; }
        public virtual Nullable<int> branchRuleId { get; set; }
        public virtual string title { get; set; }
        public bool Cache { get; set; }
    
        public virtual def_BranchRules def_BranchRules { get; set; }
        public virtual ICollection<def_FormParts> def_FormParts { get; set; }
        public virtual ICollection<def_PartSections> def_PartSections { get; set; }
        public virtual ICollection<def_PartText> def_PartText { get; set; }
    }
}
