//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_WebServiceActivityFunctions
    {
        public def_WebServiceActivityFunctions()
        {
            this.def_WebServiceActivity = new HashSet<def_WebServiceActivity>();
        }
    
        public int ActivityID { get; set; }
        public string ActivityName { get; set; }
    
        public virtual ICollection<def_WebServiceActivity> def_WebServiceActivity { get; set; }
    }
}
