//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_LookupMaster
    {
        public def_LookupMaster()
        {
            this.def_LookupDetail = new HashSet<def_LookupDetail>();
        }
    
        public virtual int lookupMasterId { get; set; }
        public virtual string lookupCode { get; set; }
        public virtual string title { get; set; }
        public virtual short baseTypeId { get; set; }
        public bool Cache { get; set; }
    
        public virtual def_BaseTypes def_BaseTypes { get; set; }
        public virtual ICollection<def_LookupDetail> def_LookupDetail { get; set; }
    }
}
