//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_WebServiceActivity
    {
        public int RequestID { get; set; }
        public Nullable<int> EnterpriseID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<System.DateTime> IssuedDateTime { get; set; }
        public Nullable<int> IssuedByUserID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public string ActivityParameters { get; set; }
        public Nullable<System.DateTime> DateTimeServiced { get; set; }
        public bool RequestFailed { get; set; }
        public string RequestServiceMsg { get; set; }
        public string SentBy { get; set; }
    
        public virtual def_WebServiceActivityFunctions def_WebServiceActivityFunctions { get; set; }
    }
}
