//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_BranchRules
    {
        public def_BranchRules()
        {
            this.def_Parts = new HashSet<def_Parts>();
            this.def_Sections = new HashSet<def_Sections>();
        }
    
        public int branchRuleId { get; set; }
        public string target { get; set; }
        public string expression { get; set; }
    
        public virtual ICollection<def_Parts> def_Parts { get; set; }
        public virtual ICollection<def_Sections> def_Sections { get; set; }
    }
}
