//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_OutcomeDeclaration
    {
        public def_OutcomeDeclaration()
        {
            this.def_ItemVariables = new HashSet<def_ItemVariables>();
        }
    
        public int outcomeDeclarationId { get; set; }
        public Nullable<float> normalMinimum { get; set; }
        public Nullable<float> normalMaximum { get; set; }
        public Nullable<float> masteryValue { get; set; }
        public string interpretation { get; set; }
    
        public virtual ICollection<def_ItemVariables> def_ItemVariables { get; set; }
    }
}
