//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_StatusMaster
    {
        public def_StatusMaster()
        {
            this.def_StatusDetail = new HashSet<def_StatusDetail>();
        }
    
        public int statusMasterId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> formId { get; set; }
        public string statusMasterTitle { get; set; }
    
        public virtual def_Forms def_Forms { get; set; }
        public virtual ICollection<def_StatusDetail> def_StatusDetail { get; set; }
    }
}
