//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_StatusLog
    {
        public int statusLogId { get; set; }
        public Nullable<int> statusDetailIdFrom { get; set; }
        public Nullable<int> statusDetailIdTo { get; set; }
        public Nullable<int> formResultId { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime statusLogDate { get; set; }
        public string statusNote { get; set; }
    
        public virtual def_FormResults def_FormResults { get; set; }
        public virtual def_StatusDetail def_StatusDetail { get; set; }
        public virtual def_StatusDetail def_StatusDetail1 { get; set; }
    }
}
