//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_SectionItemsEnt
    {
        public virtual int sectionItemEntId { get; set; }
        public virtual int sectionItemId { get; set; }
        public virtual int validation { get; set; }
        public virtual bool display { get; set; }
        public virtual bool readOnly { get; set; }
        public virtual bool requiredSection { get; set; }
        public virtual bool requiredForm { get; set; }
        public virtual int EnterpriseID { get; set; }
        public bool Cache { get; set; }
    
        public virtual def_SectionItems def_SectionItems { get; set; }
    }
}
