//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_FormVariants
    {
        public int formVariantID { get; set; }
        public int formID { get; set; }
        public string identifier { get; set; }
        public string title { get; set; }
        public int EnterpriseID { get; set; }
        public int displayOrder { get; set; }
    }
}
