//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_RelatedEnum
    {
        public def_RelatedEnum()
        {
            this.def_FileAttachment = new HashSet<def_FileAttachment>();
        }
    
        public int RelatedEnumId { get; set; }
        public string EnumDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<def_FileAttachment> def_FileAttachment { get; set; }
    }
}
