//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_AttachType
    {
        public def_AttachType()
        {
            this.def_FileAttachment = new HashSet<def_FileAttachment>();
        }
    
        public virtual int AttachTypeId { get; set; }
        public virtual string AttachDescription { get; set; }
        public virtual System.DateTime CreatedDate { get; set; }
        public virtual int CreatedBy { get; set; }
        public bool Cache { get; set; }
    
        public virtual ICollection<def_FileAttachment> def_FileAttachment { get; set; }
    }
}
