//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class def_PartSections
    {
        public def_PartSections()
        {
            this.def_PartSectionsEnt = new HashSet<def_PartSectionsEnt>();
            this.def_PartSectionsEnt1 = new HashSet<def_PartSectionsEnt>();
        }
    
        public virtual int partSectionId { get; set; }
        public virtual int partId { get; set; }
        public virtual int sectionId { get; set; }
        public virtual Nullable<short> order { get; set; }
        public virtual Nullable<bool> visible { get; set; }
        public bool Cache { get; set; }
    
        public virtual def_Parts def_Parts { get; set; }
        public virtual def_Sections def_Sections { get; set; }
        public virtual ICollection<def_PartSectionsEnt> def_PartSectionsEnt { get; set; }
        public virtual ICollection<def_PartSectionsEnt> def_PartSectionsEnt1 { get; set; }
    }
}
