//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_EntGrpPhone
    {
        public int EntGrpPhoneID { get; set; }
        public int EnterpriseID { get; set; }
        public int GroupID { get; set; }
        public string PhoneType { get; set; }
        public string PhoneNumber { get; set; }
        public string FullPhoneNumber { get; set; }
        public string FormatPreference { get; set; }
        public string CountryRegion { get; set; }
        public string CityAreaCode { get; set; }
        public string Extension { get; set; }
        public string Priority { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual uas_Enterprise uas_Enterprise { get; set; }
        public virtual uas_User uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
        public virtual uas_Group uas_Group { get; set; }
    }
}
