//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_RoleAppPermissions
    {
        public uas_RoleAppPermissions()
        {
            this.uas_GroupUserAppPermissions = new HashSet<uas_GroupUserAppPermissions>();
        }
    
        public int RoleAppPermissionsID { get; set; }
        public int RoleID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string StatusFlag { get; set; }
        public string SecuritySet { get; set; }
        public Nullable<int> ApplicationID { get; set; }
    
        public virtual ICollection<uas_GroupUserAppPermissions> uas_GroupUserAppPermissions { get; set; }
        public virtual uas_Role uas_Role { get; set; }
        public virtual uas_User uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
    }
}
