//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_GroupUserAppPermissions
    {
        public int GroupUserAppPermissionsID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public int UserID { get; set; }
        public int RoleAppPermissionsID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string StatusFlag { get; set; }
        public int ApplicationID { get; set; }
        public string SecuritySet { get; set; }
    
        public virtual uas_Group uas_Group { get; set; }
        public virtual uas_RoleAppPermissions uas_RoleAppPermissions { get; set; }
        public virtual uas_User uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
        public virtual uas_User uas_User11 { get; set; }
    }
}
