//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_Group
    {
        public uas_Group()
        {
            this.uas_GroupUserAppPermissions = new HashSet<uas_GroupUserAppPermissions>();
            this.uas_Group1 = new HashSet<uas_Group>();
            this.uas_EntGrpAddress = new HashSet<uas_EntGrpAddress>();
            this.uas_EntGrpEmail = new HashSet<uas_EntGrpEmail>();
            this.uas_EntGrpPhone = new HashSet<uas_EntGrpPhone>();
            this.uas_License = new HashSet<uas_License>();
            this.uas_UserLoginActivity = new HashSet<uas_UserLoginActivity>();
        }
    
        public int GroupID { get; set; }
        public int GroupTypeID { get; set; }
        public int EnterpriseID { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> ParentGroupId { get; set; }
    
        public virtual uas_Enterprise uas_Enterprise { get; set; }
        public virtual ICollection<uas_GroupUserAppPermissions> uas_GroupUserAppPermissions { get; set; }
        public virtual ICollection<uas_Group> uas_Group1 { get; set; }
        public virtual uas_Group uas_Group2 { get; set; }
        public virtual uas_User uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
        public virtual ICollection<uas_EntGrpAddress> uas_EntGrpAddress { get; set; }
        public virtual ICollection<uas_EntGrpEmail> uas_EntGrpEmail { get; set; }
        public virtual ICollection<uas_EntGrpPhone> uas_EntGrpPhone { get; set; }
        public virtual uas_GroupType uas_GroupType { get; set; }
        public virtual ICollection<uas_License> uas_License { get; set; }
        public virtual ICollection<uas_UserLoginActivity> uas_UserLoginActivity { get; set; }
    }
}
