//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_Enterprise
    {
        public uas_Enterprise()
        {
            this.uas_Group = new HashSet<uas_Group>();
            this.uas_Role = new HashSet<uas_Role>();
            this.uas_User = new HashSet<uas_User>();
            this.uas_EntAppConfig = new HashSet<uas_EntAppConfig>();
            this.uas_ConfirmationQueue = new HashSet<uas_ConfirmationQueue>();
            this.uas_EmailQueue = new HashSet<uas_EmailQueue>();
            this.uas_EntConfig = new HashSet<uas_EntConfig>();
            this.uas_EntGrpAddress = new HashSet<uas_EntGrpAddress>();
            this.uas_EntGrpEmail = new HashSet<uas_EntGrpEmail>();
            this.uas_EntGrpPhone = new HashSet<uas_EntGrpPhone>();
            this.uas_GroupType = new HashSet<uas_GroupType>();
            this.uas_License = new HashSet<uas_License>();
            this.uas_UserLoginActivity = new HashSet<uas_UserLoginActivity>();
        }
    
        public int EnterpriseID { get; set; }
        public int ConfigID { get; set; }
        public string EnterpriseName { get; set; }
        public string EnterpriseDescription { get; set; }
        public string ConfigParams { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string StatusFlag { get; set; }
    
        public virtual uas_Config uas_Config { get; set; }
        public virtual ICollection<uas_Group> uas_Group { get; set; }
        public virtual ICollection<uas_Role> uas_Role { get; set; }
        public virtual ICollection<uas_User> uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
        public virtual uas_User uas_User11 { get; set; }
        public virtual ICollection<uas_EntAppConfig> uas_EntAppConfig { get; set; }
        public virtual ICollection<uas_ConfirmationQueue> uas_ConfirmationQueue { get; set; }
        public virtual ICollection<uas_EmailQueue> uas_EmailQueue { get; set; }
        public virtual ICollection<uas_EntConfig> uas_EntConfig { get; set; }
        public virtual ICollection<uas_EntGrpAddress> uas_EntGrpAddress { get; set; }
        public virtual ICollection<uas_EntGrpEmail> uas_EntGrpEmail { get; set; }
        public virtual ICollection<uas_EntGrpPhone> uas_EntGrpPhone { get; set; }
        public virtual ICollection<uas_GroupType> uas_GroupType { get; set; }
        public virtual ICollection<uas_License> uas_License { get; set; }
        public virtual uas_PasswordRestriction uas_PasswordRestriction { get; set; }
        public virtual ICollection<uas_UserLoginActivity> uas_UserLoginActivity { get; set; }
    }
}
