//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_Role
    {
        public uas_Role()
        {
            this.uas_RoleAppPermissions = new HashSet<uas_RoleAppPermissions>();
            this.uas_UserLoginActivity = new HashSet<uas_UserLoginActivity>();
        }
    
        public int RoleID { get; set; }
        public int RoleTypeID { get; set; }
        public int EnterpriseID { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string StatusFlag { get; set; }
    
        public virtual uas_Enterprise uas_Enterprise { get; set; }
        public virtual ICollection<uas_RoleAppPermissions> uas_RoleAppPermissions { get; set; }
        public virtual uas_User uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
        public virtual ICollection<uas_UserLoginActivity> uas_UserLoginActivity { get; set; }
    }
}
