//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_License
    {
        public int LicenseID { get; set; }
        public int EnterpriseID { get; set; }
        public int GroupID { get; set; }
        public int LicensePoolID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int PoolReserved { get; set; }
        public int PoolTotal { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual uas_Enterprise uas_Enterprise { get; set; }
        public virtual uas_Group uas_Group { get; set; }
        public virtual uas_User uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
        public virtual uas_User uas_User2 { get; set; }
    }
}
