//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_Config
    {
        public uas_Config()
        {
            this.uas_Enterprise = new HashSet<uas_Enterprise>();
            this.uas_ProfileConfig = new HashSet<uas_ProfileConfig>();
            this.uas_GroupType = new HashSet<uas_GroupType>();
        }
    
        public int ConfigID { get; set; }
        public string ConfigName { get; set; }
        public string ConfigParams { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<uas_Enterprise> uas_Enterprise { get; set; }
        public virtual ICollection<uas_ProfileConfig> uas_ProfileConfig { get; set; }
        public virtual uas_User uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
        public virtual ICollection<uas_GroupType> uas_GroupType { get; set; }
    }
}
