//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_StatusFlagType
    {
        public int StatusFlagTypeID { get; set; }
        public string PertainsTo { get; set; }
        public string StatusFlag { get; set; }
        public string Description { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual uas_User uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
    }
}
