//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_UserAddress
    {
        public int UserAddressID { get; set; }
        public int UserID { get; set; }
        public string AddressType { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string StateProvince { get; set; }
        public string County { get; set; }
        public string Country { get; set; }
        public string Priority { get; set; }
        public Nullable<bool> Archive { get; set; }
        public string URL { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool MayContact { get; set; }
    
        public virtual uas_User uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
        public virtual uas_User uas_User2 { get; set; }
    }
}
