//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_User
    {
        public uas_User()
        {
            this.uas_GroupUserAppPermissions = new HashSet<uas_GroupUserAppPermissions>();
            this.uas_SecretQuestionAnswer = new HashSet<uas_SecretQuestionAnswer>();
            this.uas_UserAddress = new HashSet<uas_UserAddress>();
            this.uas_UserEmail = new HashSet<uas_UserEmail>();
            this.uas_UserPhone = new HashSet<uas_UserPhone>();
            this.uas_User1 = new HashSet<uas_User>();
            this.uas_UserProfile = new HashSet<uas_UserProfile>();
            this.uas_Config = new HashSet<uas_Config>();
            this.uas_Config1 = new HashSet<uas_Config>();
            this.uas_Enterprise1 = new HashSet<uas_Enterprise>();
            this.uas_Enterprise11 = new HashSet<uas_Enterprise>();
            this.uas_Group = new HashSet<uas_Group>();
            this.uas_Group1 = new HashSet<uas_Group>();
            this.uas_GroupUserAppPermissions1 = new HashSet<uas_GroupUserAppPermissions>();
            this.uas_GroupUserAppPermissions11 = new HashSet<uas_GroupUserAppPermissions>();
            this.uas_ProfileConfig = new HashSet<uas_ProfileConfig>();
            this.uas_ProfileConfig1 = new HashSet<uas_ProfileConfig>();
            this.uas_Role = new HashSet<uas_Role>();
            this.uas_Role1 = new HashSet<uas_Role>();
            this.uas_RoleAppPermissions = new HashSet<uas_RoleAppPermissions>();
            this.uas_RoleAppPermissions1 = new HashSet<uas_RoleAppPermissions>();
            this.uas_SecretQuestion = new HashSet<uas_SecretQuestion>();
            this.uas_SecretQuestion1 = new HashSet<uas_SecretQuestion>();
            this.uas_SecretQuestionAnswer1 = new HashSet<uas_SecretQuestionAnswer>();
            this.uas_SecretQuestionAnswer11 = new HashSet<uas_SecretQuestionAnswer>();
            this.uas_StatusFlagType = new HashSet<uas_StatusFlagType>();
            this.uas_StatusFlagType1 = new HashSet<uas_StatusFlagType>();
            this.uas_User11 = new HashSet<uas_User>();
            this.uas_User12 = new HashSet<uas_User>();
            this.uas_UserAddress1 = new HashSet<uas_UserAddress>();
            this.uas_UserAddress2 = new HashSet<uas_UserAddress>();
            this.uas_UserEmail1 = new HashSet<uas_UserEmail>();
            this.uas_UserEmail2 = new HashSet<uas_UserEmail>();
            this.uas_UserPhone1 = new HashSet<uas_UserPhone>();
            this.uas_UserPhone2 = new HashSet<uas_UserPhone>();
            this.uas_UserProfile1 = new HashSet<uas_UserProfile>();
            this.uas_UserProfile2 = new HashSet<uas_UserProfile>();
            this.uas_EntAppConfig = new HashSet<uas_EntAppConfig>();
            this.uas_EntAppConfig1 = new HashSet<uas_EntAppConfig>();
            this.uas_ConfirmationQueue = new HashSet<uas_ConfirmationQueue>();
            this.uas_ConfirmationQueue1 = new HashSet<uas_ConfirmationQueue>();
            this.uas_ConfirmationQueue2 = new HashSet<uas_ConfirmationQueue>();
            this.uas_EmailQueue = new HashSet<uas_EmailQueue>();
            this.uas_EmailQueue1 = new HashSet<uas_EmailQueue>();
            this.uas_EmailQueue2 = new HashSet<uas_EmailQueue>();
            this.uas_EntConfig = new HashSet<uas_EntConfig>();
            this.uas_EntConfig1 = new HashSet<uas_EntConfig>();
            this.uas_EntGrpAddress = new HashSet<uas_EntGrpAddress>();
            this.uas_EntGrpAddress1 = new HashSet<uas_EntGrpAddress>();
            this.uas_EntGrpEmail = new HashSet<uas_EntGrpEmail>();
            this.uas_EntGrpEmail1 = new HashSet<uas_EntGrpEmail>();
            this.uas_EntGrpPhone = new HashSet<uas_EntGrpPhone>();
            this.uas_EntGrpPhone1 = new HashSet<uas_EntGrpPhone>();
            this.uas_GroupType = new HashSet<uas_GroupType>();
            this.uas_GroupType1 = new HashSet<uas_GroupType>();
            this.uas_License = new HashSet<uas_License>();
            this.uas_License1 = new HashSet<uas_License>();
            this.uas_License2 = new HashSet<uas_License>();
            this.uas_PasswordRestriction = new HashSet<uas_PasswordRestriction>();
            this.uas_PasswordRestriction1 = new HashSet<uas_PasswordRestriction>();
            this.uas_UserLoginActivity = new HashSet<uas_UserLoginActivity>();
            this.uas_UserLoginActivity1 = new HashSet<uas_UserLoginActivity>();
            this.uas_UserLoginActivity2 = new HashSet<uas_UserLoginActivity>();
        }
    
        public int UserID { get; set; }
        public int EnterpriseID { get; set; }
        public string UserKey { get; set; }
        public string LoginID { get; set; }
        public string Domain { get; set; }
        public string DomainUserID { get; set; }
        public string Password { get; set; }
        public string TempPassword { get; set; }
        public string UserName { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public bool ChangePassword { get; set; }
        public string Title { get; set; }
        public string Area { get; set; }
        public string Region { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int LoginAttempts { get; set; }
        public bool AccountLocked { get; set; }
        public string LockedReason { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string StatusFlag { get; set; }
        public bool IsReserved { get; set; }
        public string PreferredLanguage { get; set; }
        public int langId { get; set; }
        public Nullable<bool> SentLockoutEmail { get; set; }
    
        public virtual uas_Enterprise uas_Enterprise { get; set; }
        public virtual ICollection<uas_GroupUserAppPermissions> uas_GroupUserAppPermissions { get; set; }
        public virtual ICollection<uas_SecretQuestionAnswer> uas_SecretQuestionAnswer { get; set; }
        public virtual ICollection<uas_UserAddress> uas_UserAddress { get; set; }
        public virtual ICollection<uas_UserEmail> uas_UserEmail { get; set; }
        public virtual ICollection<uas_UserPhone> uas_UserPhone { get; set; }
        public virtual ICollection<uas_User> uas_User1 { get; set; }
        public virtual uas_User uas_User2 { get; set; }
        public virtual ICollection<uas_UserProfile> uas_UserProfile { get; set; }
        public virtual ICollection<uas_Config> uas_Config { get; set; }
        public virtual ICollection<uas_Config> uas_Config1 { get; set; }
        public virtual ICollection<uas_Enterprise> uas_Enterprise1 { get; set; }
        public virtual ICollection<uas_Enterprise> uas_Enterprise11 { get; set; }
        public virtual ICollection<uas_Group> uas_Group { get; set; }
        public virtual ICollection<uas_Group> uas_Group1 { get; set; }
        public virtual ICollection<uas_GroupUserAppPermissions> uas_GroupUserAppPermissions1 { get; set; }
        public virtual ICollection<uas_GroupUserAppPermissions> uas_GroupUserAppPermissions11 { get; set; }
        public virtual ICollection<uas_ProfileConfig> uas_ProfileConfig { get; set; }
        public virtual ICollection<uas_ProfileConfig> uas_ProfileConfig1 { get; set; }
        public virtual ICollection<uas_Role> uas_Role { get; set; }
        public virtual ICollection<uas_Role> uas_Role1 { get; set; }
        public virtual ICollection<uas_RoleAppPermissions> uas_RoleAppPermissions { get; set; }
        public virtual ICollection<uas_RoleAppPermissions> uas_RoleAppPermissions1 { get; set; }
        public virtual ICollection<uas_SecretQuestion> uas_SecretQuestion { get; set; }
        public virtual ICollection<uas_SecretQuestion> uas_SecretQuestion1 { get; set; }
        public virtual ICollection<uas_SecretQuestionAnswer> uas_SecretQuestionAnswer1 { get; set; }
        public virtual ICollection<uas_SecretQuestionAnswer> uas_SecretQuestionAnswer11 { get; set; }
        public virtual ICollection<uas_StatusFlagType> uas_StatusFlagType { get; set; }
        public virtual ICollection<uas_StatusFlagType> uas_StatusFlagType1 { get; set; }
        public virtual ICollection<uas_User> uas_User11 { get; set; }
        public virtual uas_User uas_User3 { get; set; }
        public virtual ICollection<uas_User> uas_User12 { get; set; }
        public virtual uas_User uas_User4 { get; set; }
        public virtual ICollection<uas_UserAddress> uas_UserAddress1 { get; set; }
        public virtual ICollection<uas_UserAddress> uas_UserAddress2 { get; set; }
        public virtual ICollection<uas_UserEmail> uas_UserEmail1 { get; set; }
        public virtual ICollection<uas_UserEmail> uas_UserEmail2 { get; set; }
        public virtual ICollection<uas_UserPhone> uas_UserPhone1 { get; set; }
        public virtual ICollection<uas_UserPhone> uas_UserPhone2 { get; set; }
        public virtual ICollection<uas_UserProfile> uas_UserProfile1 { get; set; }
        public virtual ICollection<uas_UserProfile> uas_UserProfile2 { get; set; }
        public virtual ICollection<uas_EntAppConfig> uas_EntAppConfig { get; set; }
        public virtual ICollection<uas_EntAppConfig> uas_EntAppConfig1 { get; set; }
        public virtual ICollection<uas_ConfirmationQueue> uas_ConfirmationQueue { get; set; }
        public virtual ICollection<uas_ConfirmationQueue> uas_ConfirmationQueue1 { get; set; }
        public virtual ICollection<uas_ConfirmationQueue> uas_ConfirmationQueue2 { get; set; }
        public virtual ICollection<uas_EmailQueue> uas_EmailQueue { get; set; }
        public virtual ICollection<uas_EmailQueue> uas_EmailQueue1 { get; set; }
        public virtual ICollection<uas_EmailQueue> uas_EmailQueue2 { get; set; }
        public virtual ICollection<uas_EntConfig> uas_EntConfig { get; set; }
        public virtual ICollection<uas_EntConfig> uas_EntConfig1 { get; set; }
        public virtual ICollection<uas_EntGrpAddress> uas_EntGrpAddress { get; set; }
        public virtual ICollection<uas_EntGrpAddress> uas_EntGrpAddress1 { get; set; }
        public virtual ICollection<uas_EntGrpEmail> uas_EntGrpEmail { get; set; }
        public virtual ICollection<uas_EntGrpEmail> uas_EntGrpEmail1 { get; set; }
        public virtual ICollection<uas_EntGrpPhone> uas_EntGrpPhone { get; set; }
        public virtual ICollection<uas_EntGrpPhone> uas_EntGrpPhone1 { get; set; }
        public virtual ICollection<uas_GroupType> uas_GroupType { get; set; }
        public virtual ICollection<uas_GroupType> uas_GroupType1 { get; set; }
        public virtual ICollection<uas_License> uas_License { get; set; }
        public virtual ICollection<uas_License> uas_License1 { get; set; }
        public virtual ICollection<uas_License> uas_License2 { get; set; }
        public virtual ICollection<uas_PasswordRestriction> uas_PasswordRestriction { get; set; }
        public virtual ICollection<uas_PasswordRestriction> uas_PasswordRestriction1 { get; set; }
        public virtual ICollection<uas_UserLoginActivity> uas_UserLoginActivity { get; set; }
        public virtual ICollection<uas_UserLoginActivity> uas_UserLoginActivity1 { get; set; }
        public virtual ICollection<uas_UserLoginActivity> uas_UserLoginActivity2 { get; set; }
    }
}
