//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class uas_EmailQueue
    {
        public int EmailQueueID { get; set; }
        public int EnterpriseID { get; set; }
        public int UserID { get; set; }
        public string AddressFrom { get; set; }
        public string AddressTo { get; set; }
        public System.DateTime TimeSent { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string StatusFlag { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual uas_User uas_User { get; set; }
        public virtual uas_User uas_User1 { get; set; }
        public virtual uas_Enterprise uas_Enterprise { get; set; }
        public virtual uas_User uas_User2 { get; set; }
    }
}
