//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEnrollmentSite
    {
        public int GroupId { get; set; }
        public string Enrollment_Site { get; set; }
        public string Site__ { get; set; }
        public string Jurisdiction { get; set; }
        public string Restrictions { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Contact { get; set; }
    }
}
