//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;

    public partial class vFormResultUser
    {
        public int formResultId { get; set; }
        public int formId { get; set; }
        public byte formStatus { get; set; }
        public byte sessionStatus { get; set; }
        public System.DateTime dateUpdated { get; set; }
        public bool deleted { get; set; }
        public bool locked { get; set; }
        public bool archived { get; set; }
        public Nullable<int> EnterpriseID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> subject { get; set; }
        public Nullable<int> interviewer { get; set; }
        public Nullable<int> assigned { get; set; }
        public bool training { get; set; }
        public byte reviewStatus { get; set; }
        public Nullable<System.DateTime> statusChangeDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string StatusFlag { get; set; }
        public string PreferredLanguage { get; set; }
        public int langId { get; set; }
        public string GroupName { get; set; }
        public string languageTitle { get; set; }
        public string languageRegion { get; set; }
        public Nullable<int> LastModifiedByUserId { get; set; }
        public string adap_id { get; set; }
        public Nullable<System.DateTime> EligibilityEndDate { get; set; }
        public string formVariant { get; set; }
    }
}
