//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSearchGrid
    {
        public Nullable<int> ent_id { get; set; }
        public Nullable<int> sub_id { get; set; }
        public Nullable<long> Recipient_ContactID { get; set; }
        public int formResultId { get; set; }
        public int formId { get; set; }
        public Nullable<int> assigned { get; set; }
        public bool deleted { get; set; }
        public bool locked { get; set; }
        public bool archived { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MedicaidNumber { get; set; }
        public string TrackingNumber { get; set; }
        public string Lst4 { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string InterviewerLoginID { get; set; }
        public string Status { get; set; }
        public string reviewStatus { get; set; }
        public string CheckedOutTo { get; set; }
        public int Rank { get; set; }
    }
}
