//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSisDefRaw
    {
        public int formResultId { get; set; }
        public string identifier { get; set; }
        public Nullable<int> rspInt { get; set; }
        public Nullable<double> rspFloat { get; set; }
        public Nullable<System.DateTime> rspDate { get; set; }
        public string rspValue { get; set; }
    }
}
