//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assmnts
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSISAssessmentsForSearch
    {
        public int formResultID { get; set; }
        public Nullable<int> formId { get; set; }
        public int GroupID { get; set; }
        public int EnterpriseID { get; set; }
        public string StatusText { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> locked { get; set; }
        public Nullable<bool> archived { get; set; }
        public Nullable<int> subject { get; set; }
        public Nullable<int> interviewer { get; set; }
        public Nullable<int> assigned { get; set; }
        public string sis_cl_last_nm { get; set; }
        public string sis_cl_first_nm { get; set; }
        public string sis_cl_middle_nm { get; set; }
        public string sis_cl_ssn { get; set; }
        public string sis_track_num { get; set; }
        public string sis_cl_medicaidNum { get; set; }
        public string sis_completed_dt { get; set; }
        public Nullable<byte> reviewStatus { get; set; }
        public string sis_checked_out_to_LoginID { get; set; }
    }
}
